// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synchrowise.Database;

#nullable disable

namespace Synchrowise.Database.Migrations
{
    [DbContext(typeof(SynchrowiseDbContext))]
    [Migration("20220313154205_signin")]
    partial class signin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Synchrowise.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Email_verified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Firebase_Creation_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Firebase_Last_Signin_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Firebase_id_token")
                        .HasColumnType("text");

                    b.Property<string>("Firebase_uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_New_user")
                        .HasColumnType("boolean");

                    b.Property<int>("PremiumType")
                        .HasColumnType("integer");

                    b.Property<string>("Signin_Method")
                        .HasColumnType("text");

                    b.Property<int>("Term_Vision")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Firebase_uid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
